name: monthly-executor

on:
  schedule:
    - cron: '0 13 1 * *'
  workflow_dispatch:

jobs:
  notify:
    name: notify
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - uses: browser-actions/setup-chrome@latest
      - run: bundle exec ruby gen_chousei.rb
